[
  {
    id: 1,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 2,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 3,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 4,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 5,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 6,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 7,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 8,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 9,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 10,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 11,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 12,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 13,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 14,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 15,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 16,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 17,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 18,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 19,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 20,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 21,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 22,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 23,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 24,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 25,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 26,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 27,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 28,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 29,
    TruckNo: "BR01GL1330",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
];

[
  {
    id: 30,
    TruckNo: "BR01GL2128",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 31,
    TruckNo: "BR01GL2128",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 32,
    TruckNo: "BR01GL2128",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
  {
    id: 33,
    TruckNo: "BR01GL2128",
    Result: "Yes",
    CheckListUser: "",
    Remark: "",
    ApprovedUser: "Sagar",
  },
];
